[settings]
lockfile = true

[tools]
node = "24"
python = "3.14"
uv = "0.10.10"
pipx = "1.8.0"
neovim = "0.11.6"

"pipx:git-filter-repo" = "2.47.0"
"npm:@devcontainers/cli" = "0.84.1"

# tmux で plan 結果が遡れない？
"npm:@github/copilot" = "1.0.36"

"syft" = "1.42.3"
"gcloud" = "565.0.0"
